DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    competition ENUM('CH', 'EL', 'CL') NOT NULL,
    pot TINYINT NULL
);

INSERT INTO teams (name, country, competition, pot) VALUES
-- Champions League
    ('ParisSaintGermain', 'France', 'CH', 1),
    ('RealMadrid', 'Spain', 'CH', 1),
    ('ManchesterCity', 'England', 'CH', 1),
    ('BayernMunich', 'Germany', 'CH', 1),
    ('Liverpool', 'England', 'CH', 1),
    ('InterMilan', 'Italy', 'CH', 1),
    ('Chelsea', 'England', 'CH', 1),
    ('BorussiaDortmund', 'Germany', 'CH', 1),
    ('Barcelona', 'Spain', 'CH', 1),
    ('Arsenal', 'England', 'CH', 2),
    ('BayerLeverkusen', 'Germany', 'CH', 2),
    ('AtleticoMadrid', 'Spain', 'CH', 2),
    ('Benfica', 'Portugal', 'CH', 2),
    ('Atalanta', 'Italy', 'CH', 2),
    ('VilaReal', 'Spain', 'CH', 2),
    ('Juventus', 'Italy', 'CH', 2),
    ('EintrachtFrankfurt', 'Germany', 'CH', 2),
    ('ClubBrugge', 'Belgium', 'CH', 2),
    ('TottenhamHotspur', 'England', 'CH', 3),
    ('PSVEindhoven', 'Netherlands', 'CH', 3),
    ('Ajax', 'Netherlands', 'CH', 3),
    ('Napoli', 'Italy', 'CH', 3),
    ('SportingCP', 'Portugal', 'CH', 3),
    ('Olympiacos', 'Greece', 'CH', 3),
    ('SlaviaPrague', 'Czechia', 'CH', 3),
    ('BodøGlimt', 'Norway', 'CH', 3),
    ('Marseille', 'France', 'CH', 3),
    ('Copenhagen', 'Denmark', 'CH', 4),
    ('Monaco', 'France', 'CH', 4),
    ('Galatasaray', 'Turkey', 'CH', 4),
    ('UnionSaintGilloise', 'Belgium', 'CH', 4),
    ('Qarabag', 'Azerbaijan', 'CH', 4),
    ('AthleticBilbao', 'Spain', 'CH', 4),
    ('NewcastleUnited', 'England', 'CH', 4),
    ('Pafos', 'Cyprus', 'CH', 4),
    ('Kairat', 'Kazakhstan', 'CH', 4),

-- Europa League
    ('Roma', 'Italy', 'EL', 5),
    ('Porto', 'Portugal', 'EL', 5),
    ('Rangers', 'Scotland', 'EL', 5),
    ('Feyenoord', 'Netherlands', 'EL', 5),
    ('Lille', 'France', 'EL', 5),
    ('DinamoZagreb', 'Croatia', 'EL', 5),
    ('RealBetis', 'Spain', 'EL', 5),
    ('RedBullSalzburg', 'Austria', 'EL', 5),
    ('AstonVilla', 'England', 'EL', 5),
    ('Fenerbahçe', 'Turkey', 'EL', 6),
    ('Braga', 'Portugal', 'EL', 6),
    ('RedStarBelgrade', 'Serbia', 'EL', 6),
    ('Lyon', 'France', 'EL', 6),
    ('PAOK', 'Greece', 'EL', 6),
    ('ViktoriaPlzen', 'Czechia', 'EL', 6),
    ('Ferencvaros', 'Hungary', 'EL', 6),
    ('Celtic', 'Scotland', 'EL', 6),
    ('YoungBoys', 'Switzerland', 'EL', 7),
    ('Basel', 'Switzerland', 'EL', 7),
    ('Midtjylland', 'Denmark', 'EL', 7),
    ('Freiburg', 'Germany', 'EL', 7),
    ('Ludogorets', 'Bulgaria', 'EL', 7),
    ('NottinghamForest', 'England', 'EL', 7),
    ('SturmGraz', 'Austria', 'EL', 7),
    ('FCSB', 'Romania', 'EL', 7),
    ('Nice', 'France', 'EL', 7),
    ('Bologna', 'Italy', 'EL', 8),
    ('CeltaVigo', 'Spain', 'EL', 8),
    ('VfBStuttgart', 'Germany', 'EL', 8),
    ('Panathinaikos', 'Greece', 'EL', 8),
    ('MalmoFF', 'Sweden', 'EL', 8),
    ('GoAheadEagles', 'Netherlands', 'EL', 8),
    ('Utrecht', 'Netherlands', 'EL', 8),
    ('Genk', 'Belgium', 'EL', 8),
    ('Brann', 'Norway', 'EL', 8),

-- Conference League
    ('Fiorentina', 'Italy', 'CL', 9),
    ('AZAlkmaar', 'Netherlands', 'CL', 9),
    ('ShakhtarDonetsk', 'Ukraine', 'CL', 9),
    ('SlovanBratislava', 'Slovakia', 'CL', 9),
    ('RapidWien', 'Austria', 'CL', 9),
    ('LegiaWarsaw', 'Poland', 'CL', 9),
    ('SpartaPrague', 'Czechia', 'CL', 9),
    ('DynamoKyiv', 'Ukraine', 'CL', 9),
    ('CrystalPalace', 'England', 'CL', 9),
    ('LechPoznan', 'Poland', 'CL', 10),
    ('RayoVallecano', 'Spain', 'CL', 10),
    ('ShamrockRovers', 'Ireland', 'CL', 10),
    ('Omonia', 'Cyprus', 'CL', 10),
    ('Mainz', 'Germany', 'CL', 10),
    ('Strasbourg', 'France', 'CL', 10),
    ('Jagiellonia', 'Poland', 'CL', 10),
    ('Celje', 'Slovenia', 'CL', 10),
    ('Rijeka', 'Croatia', 'CL', 10),
    ('ZrinjskiMostar', 'Bosnia and Herzegovina', 'CL', 11),
    ('LincolnRedImps', 'Gibraltar', 'CL', 11),
    ('KuPSKuopio', 'Finland', 'CL', 11),
    ('AEKAthens', 'Greece', 'CL', 11),
    ('Aberdeen', 'Scotland', 'CL', 11),
    ('Drita', 'Kosovo', 'CL', 11),
    ('Breiðablik', 'Iceland', 'CL', 11),
    ('SigmaOlomouc', 'Czechia', 'CL', 11),
    ('Samsunspor', 'Turkey', 'CL', 11),
    ('RakowCzęstochowa', 'Poland', 'CL', 12),
    ('AEKLarnaca', 'Cyprus', 'CL', 12),
    ('Shkendija', 'North Macedonia', 'CL', 12),
    ('BKHacken', 'Sweden', 'CL', 12),
    ('LausanneSport', 'Switzerland', 'CL', 12),
    ('UniversitateaCraiova', 'Romania', 'CL', 12),
    ('HamrunSpartans', 'Malta', 'CL', 12),
    ('Noah', 'Armenia', 'CL', 12),
    ('Shelbourne', 'Ireland', 'CL', 12);