DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    competition ENUM('CH', 'EL', 'CL') NOT NULL,
    pot TINYINT NULL
);

INSERT INTO teams (name, country, competition, pot) VALUES
-- Champions League
    ('Paris Saint-Germain', 'France', 'CH', 1),
    ('Real Madrid', 'Spain', 'CH', 1),
    ('Manchester City', 'England', 'CH', 1),
    ('Bayern Munich', 'Germany', 'CH', 1),
    ('Liverpool', 'England', 'CH', 1),
    ('Inter Milan', 'Italy', 'CH', 1),
    ('Chelsea', 'England', 'CH', 1),
    ('Borussia Dortmund', 'Germany', 'CH', 1),
    ('Barcelona', 'Spain', 'CH', 1),
    ('Arsenal', 'England', 'CH', 2),
    ('Bayer Leverkusen', 'Germany', 'CH', 2),
    ('Atlético Madrid', 'Spain', 'CH', 2),
    ('Benfica', 'Portugal', 'CH', 2),
    ('Atalanta', 'Italy', 'CH', 2),
    ('Vila-real', 'Spain', 'CH', 2),
    ('Juventus', 'Italy', 'CH', 2),
    ('Eintracht Frankfurt', 'Germany', 'CH', 2),
    ('Club Brugge', 'Belgium', 'CH', 2),
    ('Tottenham Hotspur', 'England', 'CH', 3),
    ('PSV Eindhoven', 'Netherlands', 'CH', 3),
    ('Ajax', 'Netherlands', 'CH', 3),
    ('Napoli', 'Italy', 'CH', 3),
    ('Sporting CP', 'Portugal', 'CH', 3),
    ('Olympiacos', 'Greece', 'CH', 3),
    ('Slavia Prague', 'Czechia', 'CH', 3),
    ('Bodø/Glimt', 'Norway', 'CH', 3),
    ('Marseille', 'France', 'CH', 3),
    ('Copenhagen', 'Denmark', 'CH', 4),
    ('Monaco', 'France', 'CH', 4),
    ('Galatasaray', 'Turkey', 'CH', 4),
    ('Union Saint-Gilloise', 'Belgium', 'CH', 4),
    ('Qarabağ', 'Azerbaijan', 'CH', 4),
    ('Athletic Bilbao', 'Spain', 'CH', 4),
    ('Newcastle United', 'England', 'CH', 4),
    ('Pafos', 'Cyprus', 'CH', 4),
    ('Kairat', 'Kazakhstan', 'CH', 4),

-- Europa League
    ('Roma', 'Italy', 'EL', 5),
    ('Porto', 'Portugal', 'EL', 5),
    ('Rangers', 'Scotland', 'EL', 5),
    ('Feyenoord', 'Netherlands', 'EL', 5),
    ('Lille', 'France', 'EL', 5),
    ('Dinamo Zagreb', 'Croatia', 'EL', 5),
    ('Real Betis', 'Spain', 'EL', 5),
    ('Red Bull Salzburg', 'Austria', 'EL', 5),
    ('Aston Villa', 'England', 'EL', 5),
    ('Fenerbahçe', 'Turkey', 'EL', 6),
    ('Braga', 'Portugal', 'EL', 6),
    ('Red Star Belgrade', 'Serbia', 'EL', 6),
    ('Lyon', 'France', 'EL', 6),
    ('PAOK', 'Greece', 'EL', 6),
    ('Viktoria Plzeň', 'Czechia', 'EL', 6),
    ('Ferencváros', 'Hungary', 'EL', 6),
    ('Celtic', 'Scotland', 'EL', 6),
    ('Young Boys', 'Switzerland', 'EL', 7),
    ('Basel', 'Switzerland', 'EL', 7),
    ('Midtjylland', 'Denmark', 'EL', 7),
    ('Freiburg', 'Germany', 'EL', 7),
    ('Ludogorets', 'Bulgaria', 'EL', 7),
    ('Nottingham Forest', 'England', 'EL', 7),
    ('Sturm Graz', 'Austria', 'EL', 7),
    ('FCSB', 'Romania', 'EL', 7),
    ('Nice', 'France', 'EL', 7),
    ('Bologna', 'Italy', 'EL', 8),
    ('Celta Vigo', 'Spain', 'EL', 8),
    ('VfB Stuttgart', 'Germany', 'EL', 8),
    ('Panathinaikos', 'Greece', 'EL', 8),
    ('Malmö FF', 'Sweden', 'EL', 8),
    ('Go Ahead Eagles', 'Netherlands', 'EL', 8),
    ('Utrecht', 'Netherlands', 'EL', 8),
    ('Genk', 'Belgium', 'EL', 8),
    ('Brann', 'Norway', 'EL', 8),

-- Conference League
    ('Fiorentina', 'Italy', 'CL', 9),
    ('AZ Alkmaar', 'Netherlands', 'CL', 9),
    ('Shakhtar Donetsk', 'Ukraine', 'CL', 9),
    ('Slovan Bratislava', 'Slovakia', 'CL', 9),
    ('Rapid Wien', 'Austria', 'CL', 9),
    ('Legia Warsaw', 'Poland', 'CL', 9),
    ('Sparta Prague', 'Czechia', 'CL', 9),
    ('Dynamo Kyiv', 'Ukraine', 'CL', 9),
    ('Crystal Palace', 'England', 'CL', 9),
    ('Lech Poznań', 'Poland', 'CL', 10),
    ('Rayo Vallecano', 'Spain', 'CL', 10),
    ('Shamrock Rovers', 'Ireland', 'CL', 10),
    ('Omonia', 'Cyprus', 'CL', 10),
    ('Mainz', 'Germany', 'CL', 10),
    ('Strasbourg', 'France', 'CL', 10),
    ('Jagiellonia Białystok', 'Poland', 'CL', 10),
    ('Celje', 'Slovenia', 'CL', 10),
    ('Rijeka', 'Croatia', 'CL', 10),
    ('Zrinjski Mostar', 'Bosnia and Herzegovina', 'CL', 11),
    ('Lincoln Red Imps', 'Gibraltar', 'CL', 11),
    ('KuPS Kuopio', 'Finland', 'CL', 11),
    ('AEK Athens', 'Greece', 'CL', 11),
    ('Aberdeen', 'Scotland', 'CL', 11),
    ('Drita', 'Kosovo', 'CL', 11),
    ('Breiðablik', 'Iceland', 'CL', 11),
    ('Sigma Olomouc', 'Czechia', 'CL', 11),
    ('Samsunspor', 'Turkey', 'CL', 11),
    ('Raków Częstochowa', 'Poland', 'CL', 12),
    ('AEK Larnaca', 'Cyprus', 'CL', 12),
    ('Shkëndija', 'North Macedonia', 'CL', 12),
    ('BK Häcken', 'Sweden', 'CL', 12),
    ('Lausanne-Sport', 'Switzerland', 'CL', 12),
    ('Universitatea Craiova', 'Romania', 'CL', 12),
    ('Hamrun Spartans', 'Malta', 'CL', 12),
    ('Noah', 'Armenia', 'CL', 12),
    ('Shelbourne', 'Ireland', 'CL', 12);